### PR TITLE
Update SBLocation.m

### PR DESCRIPTION
**Pull request by Gammlerfreak**
import of objc-geohash is wrong

### CODE REVIEW

**Comment by tagyro** [comment]
@Gammlerfreak the suggested change breaks the build (see travis details); we know about this issue and we suggest switching to using frameworks (`use_frameworks!` in your podfile) and then simply `@import objc_geohash`

**Comment by Gammlerfreak** [comment]
I got following error, if i use use_frameworks:

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by tagyro** [comment]
Does running a `pod install` fix it?

**Comment by Gammlerfreak** [comment]
no it dowsnt fix it

**Comment by tagyro** [comment]
In **your** podfile write:  
`use_frameworks!`  
in **your** class, where you want to use the SDK:
`@import SensorbergSDK`
Then, run `pod update` and it should be ok.
Just tested this now on a small project.

**Comment by Gammlerfreak** [comment]
it works thanks

**Pull request closed without merging**
